export const LocalStorage = {
    set: (storageKey, value) => localStorage.setItem(storageKey, JSON.stringify(value)),
    get: storageKey => JSON.parse(localStorage.getItem(storageKey)),
    remove: storageKey => localStorage.removeItem(storageKey),
}

export const LOCAL_STORAGE_KEY = {
    CUSTOMER: 'CUSTOMER',
    HIDE_INTRO: 'HIDE_INTRO',
    SHOW_CUSTOMER_COMPANIES_WARNING:'HIDE_CUSTOMER_COMPANIES_WARNING',
    CUSTOMER_COMPANIES: 'CUSTOMER_COMPANIES',
    IS_TRUSTED_CUSTOMER: 'IS_TRUSTED_CUSTOMER',
    COMPANY_SEARCH_RESULT: 'COMPANY_SEARCH_RESULT',
    COMPANY_ID_FOR_EDIT_MENU: 'COMPANY_ID_FOR_EDIT_MENU',
    COMPANY_CANDIDATE_TO_EDIT: 'COMPANY_CANDIDATE_TO_EDIT',
    MENU_ITEM_CANDIDATE_TO_EDIT: 'MENU_ITEM_CANDIDATE_TO_EDIT',
    COMPANY_SEARCH_SELECTED_CITY: 'COMPANY_SEARCH_SELECTED_CITY',
    COMPANY_SEARCH_SELECTED_REGION: 'COMPANY_SEARCH_SELECTED_REGION',
}