export const initialValues = {
    name: '',
    city: '',
    street: '',
    phone: '',
    monIsChecked: false,
    monFrom: '09:00',
    monTo: '21:00',
    tueIsChecked: false,
    tueFrom: '09:00',
    tueTo: '21:00',
    wedIsChecked: false,
    wedFrom: '09:00',
    wedTo: '21:00',
    thuIsChecked: false,
    thuFrom: '09:00',
    thuTo: '21:00',
    friIsChecked: false,
    friFrom: '09:00',
    friTo: '21:00',
    satIsChecked: false,
    satFrom: '09:00',
    satTo: '21:00',
    sunIsChecked: false,
    sunFrom: '09:00',
    sunTo: '21:00',
}